import { Lang } from "./i18n";

interface CountryEntry {
  zh: string;
  en: string;
}

export const COUNTRIES: CountryEntry[] = [
  { zh: "阿富汗", en: "Afghanistan" },
  { zh: "阿爾巴尼亞", en: "Albania" },
  { zh: "阿爾及利亞", en: "Algeria" },
  { zh: "安道爾", en: "Andorra" },
  { zh: "安哥拉", en: "Angola" },
  { zh: "安提瓜和巴布達", en: "Antigua and Barbuda" },
  { zh: "阿根廷", en: "Argentina" },
  { zh: "亞美尼亞", en: "Armenia" },
  { zh: "澳洲", en: "Australia" },
  { zh: "奧地利", en: "Austria" },
  { zh: "阿塞拜疆", en: "Azerbaijan" },
  { zh: "巴哈馬", en: "Bahamas" },
  { zh: "巴林", en: "Bahrain" },
  { zh: "孟加拉國", en: "Bangladesh" },
  { zh: "巴巴多斯", en: "Barbados" },
  { zh: "白俄羅斯", en: "Belarus" },
  { zh: "比利時", en: "Belgium" },
  { zh: "伯利茲", en: "Belize" },
  { zh: "貝寧", en: "Benin" },
  { zh: "不丹", en: "Bhutan" },
  { zh: "玻利維亞", en: "Bolivia" },
  { zh: "波斯尼亞和黑塞哥維那", en: "Bosnia and Herzegovina" },
  { zh: "博茨瓦納", en: "Botswana" },
  { zh: "巴西", en: "Brazil" },
  { zh: "文萊", en: "Brunei" },
  { zh: "保加利亞", en: "Bulgaria" },
  { zh: "布基納法索", en: "Burkina Faso" },
  { zh: "布隆迪", en: "Burundi" },
  { zh: "柬埔寨", en: "Cambodia" },
  { zh: "喀麥隆", en: "Cameroon" },
  { zh: "加拿大", en: "Canada" },
  { zh: "佛得角", en: "Cape Verde" },
  { zh: "中非共和國", en: "Central African Republic" },
  { zh: "乍得", en: "Chad" },
  { zh: "智利", en: "Chile" },
  { zh: "中國", en: "China" },
  { zh: "哥倫比亞", en: "Colombia" },
  { zh: "科摩羅", en: "Comoros" },
  { zh: "剛果（布）", en: "Republic of the Congo" },
  { zh: "剛果（金）", en: "Democratic Republic of the Congo" },
  { zh: "哥斯達黎加", en: "Costa Rica" },
  { zh: "克羅地亞", en: "Croatia" },
  { zh: "古巴", en: "Cuba" },
  { zh: "塞浦路斯", en: "Cyprus" },
  { zh: "捷克", en: "Czech Republic" },
  { zh: "丹麥", en: "Denmark" },
  { zh: "吉布提", en: "Djibouti" },
  { zh: "多米尼克", en: "Dominica" },
  { zh: "多米尼加共和國", en: "Dominican Republic" },
  { zh: "厄瓜多爾", en: "Ecuador" },
  { zh: "埃及", en: "Egypt" },
  { zh: "薩爾瓦多", en: "El Salvador" },
  { zh: "赤道幾內亞", en: "Equatorial Guinea" },
  { zh: "厄立特里亞", en: "Eritrea" },
  { zh: "愛沙尼亞", en: "Estonia" },
  { zh: "斯威士蘭", en: "Eswatini" },
  { zh: "埃塞俄比亞", en: "Ethiopia" },
  { zh: "斐濟", en: "Fiji" },
  { zh: "芬蘭", en: "Finland" },
  { zh: "法國", en: "France" },
  { zh: "加蓬", en: "Gabon" },
  { zh: "岡比亞", en: "Gambia" },
  { zh: "格魯吉亞", en: "Georgia" },
  { zh: "德國", en: "Germany" },
  { zh: "加納", en: "Ghana" },
  { zh: "希臘", en: "Greece" },
  { zh: "格林納達", en: "Grenada" },
  { zh: "危地馬拉", en: "Guatemala" },
  { zh: "幾內亞", en: "Guinea" },
  { zh: "幾內亞比紹", en: "Guinea-Bissau" },
  { zh: "圭亞那", en: "Guyana" },
  { zh: "海地", en: "Haiti" },
  { zh: "洪都拉斯", en: "Honduras" },
  { zh: "香港", en: "Hong Kong" },
  { zh: "匈牙利", en: "Hungary" },
  { zh: "冰島", en: "Iceland" },
  { zh: "印度", en: "India" },
  { zh: "印度尼西亞", en: "Indonesia" },
  { zh: "伊朗", en: "Iran" },
  { zh: "伊拉克", en: "Iraq" },
  { zh: "愛爾蘭", en: "Ireland" },
  { zh: "以色列", en: "Israel" },
  { zh: "意大利", en: "Italy" },
  { zh: "牙買加", en: "Jamaica" },
  { zh: "日本", en: "Japan" },
  { zh: "約旦", en: "Jordan" },
  { zh: "哈薩克斯坦", en: "Kazakhstan" },
  { zh: "肯尼亞", en: "Kenya" },
  { zh: "基里巴斯", en: "Kiribati" },
  { zh: "科索沃", en: "Kosovo" },
  { zh: "朝鮮", en: "North Korea" },
  { zh: "韓國", en: "South Korea" },
  { zh: "科威特", en: "Kuwait" },
  { zh: "吉爾吉斯斯坦", en: "Kyrgyzstan" },
  { zh: "老撾", en: "Laos" },
  { zh: "拉脫維亞", en: "Latvia" },
  { zh: "黎巴嫩", en: "Lebanon" },
  { zh: "萊索托", en: "Lesotho" },
  { zh: "利比里亞", en: "Liberia" },
  { zh: "利比亞", en: "Libya" },
  { zh: "列支敦士登", en: "Liechtenstein" },
  { zh: "立陶宛", en: "Lithuania" },
  { zh: "盧森堡", en: "Luxembourg" },
  { zh: "澳門", en: "Macau" },
  { zh: "馬達加斯加", en: "Madagascar" },
  { zh: "馬拉維", en: "Malawi" },
  { zh: "馬來西亞", en: "Malaysia" },
  { zh: "馬爾代夫", en: "Maldives" },
  { zh: "馬里", en: "Mali" },
  { zh: "馬耳他", en: "Malta" },
  { zh: "馬紹爾群島", en: "Marshall Islands" },
  { zh: "毛里塔尼亞", en: "Mauritania" },
  { zh: "毛里求斯", en: "Mauritius" },
  { zh: "墨西哥", en: "Mexico" },
  { zh: "密克羅尼西亞", en: "Micronesia" },
  { zh: "摩爾多瓦", en: "Moldova" },
  { zh: "摩納哥", en: "Monaco" },
  { zh: "蒙古", en: "Mongolia" },
  { zh: "黑山", en: "Montenegro" },
  { zh: "摩洛哥", en: "Morocco" },
  { zh: "莫桑比克", en: "Mozambique" },
  { zh: "緬甸", en: "Myanmar" },
  { zh: "納米比亞", en: "Namibia" },
  { zh: "瑙魯", en: "Nauru" },
  { zh: "尼泊爾", en: "Nepal" },
  { zh: "荷蘭", en: "Netherlands" },
  { zh: "新西蘭", en: "New Zealand" },
  { zh: "尼加拉瓜", en: "Nicaragua" },
  { zh: "尼日爾", en: "Niger" },
  { zh: "尼日利亞", en: "Nigeria" },
  { zh: "北馬其頓", en: "North Macedonia" },
  { zh: "挪威", en: "Norway" },
  { zh: "阿曼", en: "Oman" },
  { zh: "巴基斯坦", en: "Pakistan" },
  { zh: "巴勒斯坦", en: "Palestine" },
  { zh: "帕勞", en: "Palau" },
  { zh: "巴拿馬", en: "Panama" },
  { zh: "巴布亞新幾內亞", en: "Papua New Guinea" },
  { zh: "巴拉圭", en: "Paraguay" },
  { zh: "秘魯", en: "Peru" },
  { zh: "菲律賓", en: "Philippines" },
  { zh: "波蘭", en: "Poland" },
  { zh: "葡萄牙", en: "Portugal" },
  { zh: "波多黎各", en: "Puerto Rico" },
  { zh: "卡塔爾", en: "Qatar" },
  { zh: "羅馬尼亞", en: "Romania" },
  { zh: "俄羅斯", en: "Russia" },
  { zh: "盧旺達", en: "Rwanda" },
  { zh: "聖基茨和尼維斯", en: "Saint Kitts and Nevis" },
  { zh: "聖盧西亞", en: "Saint Lucia" },
  { zh: "聖文森特和格林納丁斯", en: "Saint Vincent and the Grenadines" },
  { zh: "薩摩亞", en: "Samoa" },
  { zh: "聖馬力諾", en: "San Marino" },
  { zh: "聖多美和普林西比", en: "Sao Tome and Principe" },
  { zh: "沙特阿拉伯", en: "Saudi Arabia" },
  { zh: "塞內加爾", en: "Senegal" },
  { zh: "塞爾維亞", en: "Serbia" },
  { zh: "塞舌爾", en: "Seychelles" },
  { zh: "塞拉利昂", en: "Sierra Leone" },
  { zh: "新加坡", en: "Singapore" },
  { zh: "斯洛伐克", en: "Slovakia" },
  { zh: "斯洛文尼亞", en: "Slovenia" },
  { zh: "所羅門群島", en: "Solomon Islands" },
  { zh: "索馬里", en: "Somalia" },
  { zh: "南非", en: "South Africa" },
  { zh: "南蘇丹", en: "South Sudan" },
  { zh: "西班牙", en: "Spain" },
  { zh: "斯里蘭卡", en: "Sri Lanka" },
  { zh: "蘇丹", en: "Sudan" },
  { zh: "蘇里南", en: "Suriname" },
  { zh: "瑞典", en: "Sweden" },
  { zh: "瑞士", en: "Switzerland" },
  { zh: "敘利亞", en: "Syria" },
  { zh: "台灣", en: "Taiwan" },
  { zh: "塔吉克斯坦", en: "Tajikistan" },
  { zh: "坦桑尼亞", en: "Tanzania" },
  { zh: "泰國", en: "Thailand" },
  { zh: "東帝汶", en: "Timor-Leste" },
  { zh: "多哥", en: "Togo" },
  { zh: "湯加", en: "Tonga" },
  { zh: "特立尼達和多巴哥", en: "Trinidad and Tobago" },
  { zh: "突尼斯", en: "Tunisia" },
  { zh: "土耳其", en: "Turkey" },
  { zh: "土庫曼斯坦", en: "Turkmenistan" },
  { zh: "圖瓦盧", en: "Tuvalu" },
  { zh: "烏干達", en: "Uganda" },
  { zh: "烏克蘭", en: "Ukraine" },
  { zh: "阿聯酋", en: "United Arab Emirates" },
  { zh: "英國", en: "United Kingdom" },
  { zh: "美國", en: "United States" },
  { zh: "烏拉圭", en: "Uruguay" },
  { zh: "烏茲別克斯坦", en: "Uzbekistan" },
  { zh: "瓦努阿圖", en: "Vanuatu" },
  { zh: "梵蒂岡", en: "Vatican City" },
  { zh: "委內瑞拉", en: "Venezuela" },
  { zh: "越南", en: "Vietnam" },
  { zh: "也門", en: "Yemen" },
  { zh: "贊比亞", en: "Zambia" },
  { zh: "津巴布韋", en: "Zimbabwe" },
];

export function getCountries(lang: Lang): string[] {
  return COUNTRIES.map((c) => c[lang]);
}
